<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2020-07-05T22:22:00" tests="0" file="cypress\integration\GetUser.feature" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Get User Details" timestamp="2020-07-05T22:22:00" tests="1" time="0.0000" failures="1">
    <testcase name="Get User Details Get User Details against virtual service" time="0.0000" classname="Get User Details against virtual service">
      <failure message="`cy.request()` failed trying to load:

http://localhost:3000/data/7

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:3000

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: http://localhost:3000/data/7

-----------------------------------------------------------

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` failed trying to load:

http://localhost:3000/data/7

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:3000

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: http://localhost:3000/data/7

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request
    at http://localhost:54636/__cypress/runner/cypress_runner.js:157585:19
    at tryCatcher (http://localhost:54636/__cypress/runner/cypress_runner.js:10161:23)
    at http://localhost:54636/__cypress/runner/cypress_runner.js:5300:37
    at tryCatcher (http://localhost:54636/__cypress/runner/cypress_runner.js:10161:23)
    at Promise._settlePromiseFromHandler (http://localhost:54636/__cypress/runner/cypress_runner.js:8096:31)
    at Promise._settlePromise (http://localhost:54636/__cypress/runner/cypress_runner.js:8153:18)
    at Promise._settlePromise0 (http://localhost:54636/__cypress/runner/cypress_runner.js:8198:10)
    at Promise._settlePromises (http://localhost:54636/__cypress/runner/cypress_runner.js:8274:18)
    at _drainQueueStep (http://localhost:54636/__cypress/runner/cypress_runner.js:4868:12)
    at _drainQueue (http://localhost:54636/__cypress/runner/cypress_runner.js:4861:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:54636/__cypress/runner/cypress_runner.js:4877:5)
    at Async.drainQueues (http://localhost:54636/__cypress/runner/cypress_runner.js:4747:14)
From Your Spec Code:
    at Context.eval (http://localhost:54636/__cypress/tests?p=cypress\integration\GetUser.feature:57:6)
    at Context.resolveAndRunStepDefinition (http://localhost:54636/__cypress/tests?p=cypress\integration\GetUser.feature:10425:9)
    at Context.eval (http://localhost:54636/__cypress/tests?p=cypress\integration\GetUser.feature:9767:35)

From Node.js Internals:
  RequestError: Error: connect ECONNREFUSED 127.0.0.1:3000
      at new RequestError (C:\Users\LA56QS\AppData\Local\Cypress\Cache\4.9.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\errors.js:14:15)
      at Request.plumbing.callback (C:\Users\LA56QS\AppData\Local\Cypress\Cache\4.9.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:87:29)
      at Request.RP$callback [as _callback] (C:\Users\LA56QS\AppData\Local\Cypress\Cache\4.9.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:46:31)
      at self.callback (C:\Users\LA56QS\AppData\Local\Cypress\Cache\4.9.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:185:22)
      at Request.emit (events.js:210:5)
      at Request.onRequestError (C:\Users\LA56QS\AppData\Local\Cypress\Cache\4.9.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:877:8)
      at ClientRequest.emit (events.js:215:7)
      at Socket.socketErrorListener (_http_client.js:406:9)
      at Socket.emit (events.js:210:5)
      at emitErrorNT (internal/streams/destroy.js:92:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
  
From Your Spec Code:
    at Context.eval (http://localhost:54636/__cypress/tests?p=cypress\integration\GetUser.feature:57:6)
    at Context.resolveAndRunStepDefinition (http://localhost:54636/__cypress/tests?p=cypress\integration\GetUser.feature:10425:9)
    at Context.eval (http://localhost:54636/__cypress/tests?p=cypress\integration\GetUser.feature:9767:35)]]></failure>
    </testcase>
  </testsuite>
</testsuites>